apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: "true"
  name: du-ptp-event-consumer-service
  labels:
      app: du-ptp-event-consumer
spec:
  ports:
    - name: sub-port
      port: 27017
      targetPort: http
  selector:
    app: du-ptp-event-consumer
  clusterIP: None
  sessionAffinity: None
  type: ClusterIP
