---
jobs:
  - name: du-workload
    jobIterations: 1
    qps: 4
    burst: 4
    namespacedIterations: false
    namespace: workload
    podWait: false
    cleanup: true
    waitWhenFinished: true
    maxWaitTimeout: 5m
    errorOnVerify: true
    objects:

    # Template of Gu Pods with fedora-stress-ng
      - objectTemplate: templates/guaranteed/configmap.yaml
        replicas: 2
      - objectTemplate: templates/guaranteed/secret.yaml
        replicas: 4
      - objectTemplate: templates/guaranteed/deployment.yaml
        replicas: 1
        inputVars:
          Image_stressng: "{{ .REGISTRY }}/fedora-stress-ng"
          Image_nginx: "{{ .REGISTRY }}/sampleapp"
          volumes:
            - name: configmap-1
              type: configMap
              path: /var/configmap1
            - name: configmap-2
              type: configMap
              path: /var/configmap2
            - name: secret-1
              type: secret
              path: /var/secret1
            - name: secret-2
              type: secret
              path: /var/secret2
            - name: secret-3
              type: secret
              path: /var/secret3
            - name: secret-4
              type: secret
              path: /var/secret4

      - objectTemplate: templates/guaranteed/service.yaml
        replicas: 1


    # Template of burstable pods with exec probes
      - objectTemplate: templates/webserver/webserver-deployment.yaml
        replicas: 4
        inputVars:
          Image_nginx: "{{ .REGISTRY }}/sampleapp"
          Image_stressng: "{{ .REGISTRY }}/fedora-stress-ng"
          volumes:
            - name: configmap-1
              type: configMap
              path: /var/configmap1
            - name: configmap-2
              type: configMap
              path: /var/configmap2
            - name: secret-1
              type: secret
              path: /var/secret1
            - name: secret-2
              type: secret
              path: /var/secret2
            - name: secret-3
              type: secret
              path: /var/secret3
            - name: secret-4
              type: secret
              path: /var/secret4
      - objectTemplate: templates/webserver/webserver-service.yaml
        replicas: 4
      - objectTemplate: templates/webserver/curl-deployment.yaml
        replicas: 4
        inputVars:
          Image_curl: "{{ .REGISTRY }}/curl"
          Image_nginx: "{{ .REGISTRY }}/sampleapp"
          volumes:
            - name: configmap-1
              type: configMap
              path: /var/configmap1
            - name: configmap-2
              type: configMap
              path: /var/configmap2
            - name: secret-1
              type: secret
              path: /var/secret1
            - name: secret-2
              type: secret
              path: /var/secret2
            - name: secret-3
              type: secret
              path: /var/secret3
            - name: secret-4
              type: secret
              path: /var/secret4

    # Templates of burstable pods with kubeapiserver reqs
      - objectTemplate: templates/kubectlapp/serviceaccount.yaml
        replicas: 6
      - objectTemplate: templates/kubectlapp/role.yaml
        replicas: 6
      - objectTemplate: templates/kubectlapp/rolebinding.yaml
        replicas: 6
      - objectTemplate: templates/kubectlapp/deployment.yaml
        replicas: 6
        inputVars:
          Image_kubectl: "{{ .REGISTRY }}/kubectl"
          Image_nginx: "{{ .REGISTRY }}/sampleapp"
          volumes:
            - name: configmap-1
              type: configMap
              path: /var/configmap1
            - name: configmap-2
              type: configMap
              path: /var/configmap2
            - name: secret-1
              type: secret
              path: /var/secret1
            - name: secret-2
              type: secret
              path: /var/secret2
            - name: secret-3
              type: secret
              path: /var/secret3
            - name: secret-4
              type: secret
              path: /var/secret4
