apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-reader-{{.Replica}}
  # namespace: workload
rules:
- apiGroups: [""]
  resources: ["pods","services"]
  verbs: ["get", "watch", "list"]