apiVersion: v1
kind: PersistentVolume
metadata:
  name: storage-io-pv-{{.Replica}}
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: standard
  hostPath:
    path: "/mnt/data"
