apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: storage-io-pvc-{{.Replica}}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
